name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4

    - name: Setup build cache
      id: build-cache
      run: |
        echo "cache-key=build-${{ github.sha }}-${{ runner.os }}-${{ github.run_id }}" >> $GITHUB_OUTPUT

    - name: Cache build dependencies
      uses: actions/cache@v4
      with:
        path: |
          deps/3rd/usr/local
          build_debug
        key: ${{ steps.build-cache.outputs.cache-key }}
        restore-keys: |
          build-${{ github.sha }}-${{ runner.os }}-
          build-${{ github.sha }}-
          build-

    - name: Init
      shell: bash
      run: sudo bash build.sh init

    - name: BuildDebug
      shell: bash
      run: bash build.sh debug -DCONCURRENCY=ON -DENABLE_COVERAGE=ON -DWITH_MEMTRACER=ON -DWITH_UNIT_TESTS=ON --make -j4

    - name: Upload debug artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build_debug/
          deps/3rd/usr/local/
        retention-days: 7

  build-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4

    - name: Setup build cache
      id: build-cache
      run: |
        echo "cache-key=build-${{ github.sha }}-${{ runner.os }}-${{ github.run_id }}" >> $GITHUB_OUTPUT

    - name: Cache build dependencies
      uses: actions/cache@v4
      with:
        path: |
          deps/3rd/usr/local
          build_release
        key: ${{ steps.build-cache.outputs.cache-key }}
        restore-keys: |
          build-${{ github.sha }}-${{ runner.os }}-
          build-${{ github.sha }}-
          build-

    - name: Init
      shell: bash
      run: sudo bash build.sh init

    - name: BuildRelease
      shell: bash
      run: bash build.sh release -DCONCURRENCY=ON -DWITH_UNIT_TESTS=OFF -DWITH_BENCHMARK=ON -DWITH_MEMTRACER=ON --make -j4

  test-on-ubuntu:
    runs-on: ubuntu-latest
    needs: build-debug

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: ./

    - name: Test
      shell: bash
      run: |
        cd build_debug
        ctest -E memtracer_test --verbose

    - name: lcov
      shell: bash
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update && sudo apt-get install -y lcov
        cd build_debug
        rm -rf unittest
        lcov -c -d ./ -o coverage.info --ignore-errors source

    - uses: codecov/codecov-action@v3
      with:
        file: build_debug/coverage.info
        token: ${{ secrets.CODECOV_TOKEN }}

  build-on-mac:
    runs-on: macos-latest

    steps:
    - name: Init environment
      shell: bash
      run: |
        brew install bison

    - name: Checkout repository and submodules
      uses: actions/checkout@v4

    - name: Setup build cache
      id: build-cache
      run: |
        echo "cache-key=build-${{ github.sha }}-${{ runner.os }}-${{ github.run_id }}" >> $GITHUB_OUTPUT

    - name: Cache build dependencies
      uses: actions/cache@v4
      with:
        path: |
          deps/3rd/usr/local
          build_release
          build_debug
        key: ${{ steps.build-cache.outputs.cache-key }}
        restore-keys: |
          build-${{ github.sha }}-${{ runner.os }}-
          build-${{ github.sha }}-
          build-
        
    - name: Build
      shell: bash
      run: |
        export ASAN_OPTIONS=detect_container_overflow=0
        export PATH="/opt/homebrew/opt/bison/bin:$PATH"
        sudo bash build.sh init
        bash build.sh debug -DWITH_MEMTRACER=ON --make -j4
        bash build.sh release -DCONCURRENCY=ON -DWITH_UNIT_TESTS=OFF -DWITH_BENCHMARK=ON -DWITH_MEMTRACER=ON --make -j4
